name: heritax
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.4.0
  flutter_inappwebview: ^6.0.0
  speech_to_text: ^7.0.0
  cupertino_icons: ^1.0.8
  smooth_page_indicator: 1.2.1
  panorama: ^0.4.1
  flutter_tts: ^4.2.2
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  lottie: ^3.3.1
  avatar_glow: ^3.0.1
  http: ^1.3.0
  shared_preferences: ^2.5.3
  sqflite: ^2.2.8+4
  path_provider: ^2.1.1
  path: ^1.8.3
  provider: ^6.0.5
  sqflite_common_ffi: any
  shared_preferences_web: ^2.1.1
  sqflite_common_ffi_web: 1.0.0
  video_player: ^2.8.3
  chewie: ^1.7.0
  photo_view: ^0.14.0
  webview_flutter: ^4.0.7
  webview_flutter_web: ^0.2.3+4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Tamil
      fonts:
        - asset: fonts/NotoSansTamil-Regular.ttf
  assets:
    - assets/images/
    - assets/panorama/
    - assets/gallery/thanjavur/gallery1.jpg
    - assets/gallery/thanjavur/gallery2.jpg
    - assets/gallery/thanjavur/gallery3.jpg
    - assets/gallery/thanjavur/gallery4.jpg
    - assets/gallery/thanjavur/gallery5.jpg
    - assets/gallery/thanjavur/gallery6.jpg
    - assets/gallery/thanjavur/gallery7.jpg
    - assets/gallery/thanjavur/gallery8.jpg
    - assets/gallery/thanjavur/gallery9.jpg
    - assets/gallery/thanjavur/gallery10.jpg
    - assets/gallery/thanjavur/gallery11.jpg
    - assets/gallery/thanjavur/gallery12.jpg
    - assets/gallery/thanjavur/gallery13.jpg
    - assets/gallery/thanjavur/gallery14.jpg
    - assets/gallery/thanjavur/gallery15.jpg
    - assets/gallery/thanjavur/gallery16.jpg
    - assets/gallery/thanjavur/v1.mp4
    - assets/gallery/thanjavur/v2.mp4
    - assets/gallery/thanjavur/v3.mp4
    - assets/gallery/thanjavur/v4.mp4
    - assets/gallery/thanjavur/v5.mp4
    - assets/gallery/nilgiri/v1.mp4
    - assets/gallery/nilgiri/v2.mp4
    - assets/gallery/nilgiri/v3.mp4
    - assets/gallery/nilgiri/v4.mp4
    - assets/gallery/nilgiri/gallery1.jpg
    - assets/gallery/nilgiri/gallery2.jpg
    - assets/gallery/nilgiri/gallery3.jpg
    - assets/gallery/nilgiri/gallery4.jpg
    - assets/gallery/nilgiri/gallery5.jpg
    - assets/gallery/nilgiri/gallery6.jpg
    - assets/gallery/nilgiri/gallery7.jpg
    - assets/gallery/nilgiri/gallery8.jpg
    - assets/gallery/nilgiri/gallery9.jpg
    - assets/gallery/gangaikonda/gallery1.jpg
    - assets/gallery/gangaikonda/gallery2.jpg
    - assets/gallery/gangaikonda/gallery3.jpg
    - assets/gallery/gangaikonda/gallery4.jpg
    - assets/gallery/gangaikonda/gallery5.jpg
    - assets/gallery/gangaikonda/gallery6.jpg
    - assets/gallery/gangaikonda/gallery7.jpg
    - assets/gallery/gangaikonda/gallery8.jpg
    - assets/gallery/gangaikonda/gallery9.jpg
    - assets/gallery/gangaikonda/gallery10.jpg
    - assets/gallery/gangaikonda/gallery12.jpg
    - assets/gallery/gangaikonda/gallery13.jpg
    - assets/gallery/gangaikonda/gallery14.jpg
    - assets/gallery/gangaikonda/gallery15.jpg
    - assets/gallery/gangaikonda/v1.mp4
    - assets/gallery/gangaikonda/v2.mp4
    - assets/gallery/gangaikonda/v3.mp4
    - assets/gallery/gangaikonda/v4.mp4

    - assets/gallery/mahabalipuram/gallery1.jpg
    - assets/gallery/mahabalipuram/gallery2.jpg

    - assets/gallery/mahabalipuram/gallery4.jpg
    - assets/gallery/mahabalipuram/gallery5.jpg
    - assets/gallery/mahabalipuram/gallery6.jpg
    - assets/gallery/mahabalipuram/gallery7.jpg
    - assets/gallery/mahabalipuram/gallery8.jpg
    - assets/gallery/mahabalipuram/gallery9.jpg
    - assets/gallery/mahabalipuram/gallery10.jpg
    - assets/gallery/mahabalipuram/gallery11.jpg
    - assets/gallery/mahabalipuram/gallery12.jpg
    - assets/gallery/mahabalipuram/v1.mp4
    - assets/gallery/mahabalipuram/v2.mp4
    - assets/gallery/mahabalipuram/v3.mp4
    - assets/gallery/mahabalipuram/v4.mp4

    - assets/gallery/airavatesvara/gallery1.jpg
    - assets/gallery/airavatesvara/gallery2.jpg
    - assets/gallery/airavatesvara/gallery3.jpg
    - assets/gallery/airavatesvara/gallery4.jpg
    - assets/gallery/airavatesvara/gallery5.jpg
    - assets/gallery/airavatesvara/gallery6.jpg

    - assets/gallery/airavatesvara/gallery7.jpg
    - assets/gallery/airavatesvara/gallery8.jpg
    - assets/gallery/airavatesvara/gallery9.jpg
    - assets/gallery/airavatesvara/gallery10.jpg
    - assets/gallery/airavatesvara/gallery11.jpg
    - assets/gallery/airavatesvara/v1.mp4
    - assets/gallery/airavatesvara/v2.mp4
    - assets/gallery/airavatesvara/v3.mp4
    - assets/gallery/airavatesvara/v4.mp4
    - assets/images/tourismbg.jpg
